// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalInputRedactionKind } from "./TerminalInputRedactionKind";

export type BackgroundTerminal = { processId: string, command: string, tty: boolean, attached: boolean, secureInputPrompt: TerminalInputRedactionKind | null, };
