// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalInputRecord } from "./TerminalInputRecord";

export type TerminalInteractionNotification = { threadId: string, turnId: string, itemId: string, processId: string, input: TerminalInputRecord, };
