// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalInputRedactionKind } from "./TerminalInputRedactionKind";

export type TerminalInputRecord = { "type": "plaintext", text: string, } | { "type": "redacted", len: number, kind: TerminalInputRedactionKind, } | { "type": "empty_poll" };
